services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"

  database:
    image: 'postgres:latest'
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_URL: "sportganise.c78uoayscpd5.us-west-2.rds.amazonaws.com"
      POSTGRES_USER: "sportganise"
      POSTGRES_PASSWORD: "capstone-sportganise"
      POSTGRES_DB: "sportganise"