services:
  frontend:
    image: ghcr.io/sisahga/sportganise-frontend:latest
    ports:
      - "80:80"
    env_file:
      - frontend/.env
    depends_on:
      - backend

  backend:
    image: ghcr.io/sisahga/sportganise-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
