name: Build and publish Docker image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sisahga/sportganise:frontend-${{ github.sha }} .

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/sisahga/sportganise:frontend-${{ github.sha }}
