name: E2E Tests
on:
  push:
    branches:
      - main
  pull_request:
    # # TODO: run only on PRs to main
    # branches:
    #   - main
jobs:
  test:
    defaults:
      run:
        working-directory: ./frontend
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    # Start backend
    - uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: ./docker-compose.e2e.yml
      env:
        POSTGRES_URL: "jdbc:postgresql://localhost:5432/sportganise"
        POSTGRES_DB: "sportganise"
        POSTGRES_USER: "sportganise"
        POSTGRES_PASSWORD: "capstone-sportganise"

    # Install pnpm
    - uses: pnpm/action-setup@v4
      with:
        version: 9.14.2
        run_install: true

    # Setup node
    - uses: actions/setup-node@v4

    # Setup Playwright
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    # Run Playwright tests
    - name: Run Playwright tests
      run: |
        echo $VITE_API_BASE_URL
        wget localhost:8080
        pnpm e2e
      env:
        VITE_API_BASE_URL: "localhost:8080"

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
