name: Build and publish Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/sisahga/sportganise:frontend-latest \
            -t ghcr.io/sisahga/sportganise:frontend-${{ github.sha }} \
            .

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/sisahga/sportganise:frontend-${{ github.sha }}
          docker push ghcr.io/sisahga/sportganise:frontend-latest

  build-and-publish-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/sisahga/sportganise:backend-latest \
            -t ghcr.io/sisahga/sportganise:backend-${{ github.sha }} \
            .

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/sisahga/sportganise:backend-${{ github.sha }}
          docker push ghcr.io/sisahga/sportganise:backend-latest
