name: CI checks backend

on:
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Run formatter
        run: mvn spotless:check --batch-mode

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Run linter
        run: mvn checkstyle:check --batch-mode -Dcheckstyle.violationSeverity=warning -Dcheckstyle.failOnViolation=true

  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
          cache: maven

      - name: Build and test
        run: mvn --batch-mode package

  build-image:
    runs-on: ubuntu-latest
    needs: [format, lint]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build .
